name: React App CI

on:
  push:
    branches: [ main ]

jobs:
  call-reusable-workflow:
    uses: abdosaad203/github-reusable-workflows/.github/workflows/node-ci-docker.yml@main
    with:
      node_version: "18"
      unit_test: false
      lint_phase: false
      docker_registry: docker.io
      docker_username: abdosaad
      docker_image_name: react-app
      docker_image_tag: latest
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
