name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: linux-vm
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t react-app:latest ./my-app

  cd:
    runs-on: linux-vm
    needs: ci
    steps:
      - name: Stop old container
        run: |
          docker stop react-app || true
          docker rm react-app || true

      - name: Run new container
        run: |
          docker run -d \
            --name react-app \
            -p 3000:3000 \
            react-app:latest
